[package]
name = "volla_messages"
version = "0.9.1-dev.1"
description = "Volla Messages"
authors = ["Tibet Sprague", "Eric Harris-Braun"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2.0", default-features = false , features = [] }

[dependencies]
tauri = { version = "2.5.1", features = ["devtools"] }
tauri-runtime = {version = "2.6.0", optional = true}
tauri-plugin-holochain = { git = "https://github.com/darksoil-studio/tauri-plugin-holochain", branch = "main-0.5", optional = true }
tauri-plugin-holochain-service-client = { version = "0.2.0", optional = true }

# datachanel webrtc backend
holochain = "0.5.6"
# go-pion webrtc back-end
#holochain = {version = "0.5.6", default-features = false, features = ["sqlite-encrypted", "wasmer_sys", "backend-go-pion"] }

holochain_types = "0.5.6"
lair_keystore = "0.6.2"
holochain_client = "0.7.1"

log = "0.4"
tauri-plugin-log = "2.4.0"
tauri-plugin-notification = "2.2.2"
tauri-plugin-clipboard-manager = "2.2.2"
tauri-plugin-sharesheet = "0.0.1"
tauri-plugin-shell = "2.2.1"
tauri-plugin-barcode-scanner = "2.2.0"
tauri-plugin-os = "2.2.1"
tauri-plugin-fs = "2.2.1"
tauri-plugin-dialog = "2.2.1"
url2 = "0.0.6"
app_dirs2 = "2.5.5"
tempdir = "0.3.7"
anyhow = "1"
serde_json = "1"
uuid = { version = "1.12.0", features = ["v4", "fast-rng"] }
base64ct = "=1.7.3"

[features]
default = []

holochain_bundled = ["dep:tauri-plugin-holochain", "dep:tauri-runtime"]
holochain_service = ["dep:tauri-plugin-holochain-service-client"]

[patch.crates-io]
wasmer-vm = { git = "https://github.com/guillemcordoba/wasmer", branch = "fix-x86" }
wasmer-types = { git = "https://github.com/guillemcordoba/wasmer", branch = "fix-x86" }
kitsune2 = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
kitsune2_api = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
kitsune2_core = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
kitsune2_dht = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
kitsune2_gossip = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
kitsune2_bootstrap_client = { git = "https://github.com/guillemcordoba/kitsune2", branch = "iroh-transport" }
